### PR TITLE
Correct .editorconfig and corresponding files

### LINKED ISSUE #281: Issue in .editorconfig file
- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.

Currently is says
```
[.{py,java}]
```
should be
```
[*.{py,java}]
```

### PR DESCRIPTION
**Pull request by singhpratyush**
Fixes #281 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [ ] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [ ] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by aviaryan** [comment]
@singhpratyush I can't get what the issue could be. Maybe this is something about the indentation of comments. 

```
coin_change_problem/CoinChange.java failed indent_char: found setting '  ', should be '    '
```

**Comment by singhpratyush** [comment]
This fixes the problem - 
```java
/*
* Implementation of famous dynamic programming problem
* that aims to find out the maximum number of ways in
* which a value can be achieved using some fixed valued
* coins.
*
* In the implementation, the time complexity is O(mn)
* and extra space required is O(n).
*/
import java.util.Arrays;
/*
* coin: Array containing value of coins
* n: Value to find the change for
*/
public class CoinChange {
    public static int coinChangeProblem(int[] C, int n) {
        int[] possibilities = new int[n+1];
        Arrays.fill(possibilities, 0);
        possibilities[0] = 1;
        ...
    }
    
    ...
}
```

Notice that spaces are removed from the comments - 
```java
/*       /*
 *   ->  *
 */      */
```

**Comment by singhpratyush** [comment]
And for the `python` code, it was
```python
    print(str(base) + ' raised to ' + str(power) + ' is ' +
            str(exponentation_by_squaring(base, power)))
```
instead of 
```python
    print(str(base) + ' raised to ' + str(power) + ' is ' +
          str(exponentation_by_squaring(base, power)))
```

The changes suggested are against `PEP8`.

**Comment by aviaryan** [comment]
@singhpratyush We can exclude python check from editorconfig-tools as coala will take care of that. (only valid if this is possible)

To fix Java as well, we will have to switch to another tool like [eclint](https://github.com/jedmao/eclint). 
See https://github.com/jedmao/eclint#support-for-doc-comments

**Comment by aviaryan** [comment]
Closing in favour of #331

**Pull request closed without merging**
