### PR TITLE
Fixed .travis.yml#21

### LINKED ISSUE #278: Improve editorconfig-tools log while testing
[`.travis.yml#21`](https://github.com/iiitv/algos/blob/master/.travis.yml#L21) says - 
```sh
editorconfig-tools check **/*
```

It can be modified so that it shows only errors that are encountered - 
```sh
editorconfig-tools check **/* | grep " failed "
```

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #278 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [ ] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [ ] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by singhpratyush** [comment]
`grep` returns non-zero if it can't find any match. How about this - 
```sh
if editorconfig-tools check **/* | grep " failed "; then false; else true; fi
```
@aviaryan @Monal5031.

**Comment by aviaryan** [comment]
@singhpratyush I am not a bash expert so can't say if that will work as expected. My first thought in this situation would be to do a `exit 1` on failed result and vice versa.

**Comment by singhpratyush** [comment]
@aviaryan That can be tested too.

**Comment by singhpratyush** [comment]
@aashutoshrathi: There is an error in `.editorconfig` file - 
```
[.{py,java}]
```
should be 
```
[*.{py,java}]
```

Please correct that and update necessary files.

**Pull request merged**
