### PR TITLE
Added  gcd, insertion sort, linear search and sieve of Eratosthenes [Haskell]

### PR DESCRIPTION
**Pull request by tgdn**
#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [X] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [X] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [X] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [X] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [X] This pull request will be closed if I fail to update it even once in a continuous timespan of 7 days.

### CODE REVIEW

**Comment by Monal5031** [comment]
@tgdn Hello thanks for contributing here, but please first read the CONTRIBUTIING.md to know how to contribute to this repo.
Please read and follow those guidelines :smiley:

**Comment by aviaryan** [comment]
@tgdn Thanks for the PR. Excited to see new contributors. 😀

Btw, as you can see, Haskell is not a supported language for this repository right now. But we are considering this at our [Gitter channel](https://gitter.im/iiitv/algos). We will let you know what we come up with.

**Comment by singhpratyush** [comment]
@tgdn: The code looks good. We are waiting for a bear for Haskell in #223. We'll be able to merge this only after that.

In the meantime, I recommend you to open issues for each of the algorithms, break this into 4 PRs and update the respective README file.

**Comment by singhpratyush** [comment]
@tgdn: Please make the requested changes. This PR will be closed upon 7 days of inactivity.

**Comment by singhpratyush** [comment]
@tgdn: Please take a look at Travis failure.

**Comment by Monal5031** [comment]
@aviaryan sir this may be closed due to inactivity.

**Comment by aviaryan** [comment]
@tgdn Since this PR is not assigned to any issue, please open this PR when you are willing to work on it later.

**Pull request closed without merging**
