### PR TITLE
Add QuickSort [C#]

### LINKED ISSUE #493: Quick Sort [C#]
#### This issue is about [Quick Sort](https://en.wikipedia.org/wiki/Quicksort).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by sebasrp**
Fixes #493

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by singhpratyush** [comment]
Hi! Thanks for showing interest in contributing to this repository.

Please make sure that you have ticked the points mentioned in PR description correctly.

Thanks again!

**Comment by sebasrp** [comment]
I am not sure why gitmate failed and how to restart the check. Can someone let me know how to do that?
Thanks

**Comment by DimaMukhin** [comment]
Looks like a duplicate of a pull request to an issue I was assigned to (https://github.com/iiitv/algos/pull/492)

**Comment by singhpratyush** [comment]
@sebasrp: Thanks for submitting the code. But as @DimaMukhin was assigned to the issue, he is the one who sends a pull request. Please read contributing guidelines carefully. :)

**Comment by sebasrp** [comment]
@DimaMukhin  and @singhpratyush 
I understand - kind of sad we are throwing away a good piece of work.
I had read the contribution guidelines, what confused me (and I think you should reconsider fixing those) is that the issue was labeled as Hacktoberfest. This is a month long event that encourages people to look for open issues in repos they wouldn't contribute normally to help out with some Pull Request.
I would recommend removing the tag if the issue is already assigned and being worked on in order to avoid these occurrences where someone with good intentions submit something that will not be considered.

**Pull request closed without merging**
