### PR TITLE
Added Haskell and Pylint to .coala

### LINKED ISSUE #222: Add HaskellLintBear and PylintBear to .coala
If we are going to add it, assign me

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #222 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [ ] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [ ] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by singhpratyush** [comment]
Try adding following install to `.tavis.yml` - 
```bash
sudo apt-get install ghc-mod hlint
```

**Comment by aashutoshrathi** [comment]
@singhpratyush sir should I add GhcModBear too ?

**Comment by singhpratyush** [comment]
I don't know if that would be needed. But I don't see it doing any harm. Please add it.

**Comment by Monal5031** [comment]
@aashutoshrathi Pylint won't be needed as PEP8Bear is already there and I think both have some different rules somewhere

**Comment by aashutoshrathi** [comment]
@Monal5031 are you sure ?

**Comment by aashutoshrathi** [comment]
@singhpratyush Sir Travis Build has now no issues with the files in this PR, it's build failed due to `k_nn.py`

**Comment by aashutoshrathi** [comment]
@singhpratyush what about those `k_nn.py` issue by PyLintBear, they should be fixed in another PR with a new issue ?

**Comment by Monal5031** [comment]
@aashutoshrathi not just `k_nn.py` other files are also the cause of the build failure.
That is why I was suggesting not to add `PyLintBear`  as we already had PEP8Bear which was just fine. PyLintBear will check things which we don't even want like variable names, but it has its own plus points too like it checks redundancy too and functions docstrings etc.

**Comment by singhpratyush** [comment]
@aashutoshrathi: You may follow [this SO thread](https://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members) to solve the issue.

**Comment by aashutoshrathi** [comment]
Should I make those changes in very same PR ? @singhpratyush

**Comment by singhpratyush** [comment]
Yes. Please update the same PR.

**Comment by benjic** [comment]
Would it be easier to move forward with the Haskell linters and follow up with the Python linter and code changes in a follow up? I'd be willing to contribute some Haskell implementations but would be stuck  locked by this.

**Comment by singhpratyush** [comment]
@benjic: Please proceed now. Make sure that you have opened an issue and added assigned to it before proceeding.

**Pull request merged**
