### PR TITLE
Added .editorconfig

### LINKED ISSUE #199: Add .editorconfig file
The `.editorconfig` file would help maintain consistency of code for the project.

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #199 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [ ] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous timespan of 7 days.

### CODE REVIEW

**Comment by aviaryan** [comment]
Comment on 68e10c66a7ed217398cffbac0be92e540985c06f, file modular_exponential/modular_exponential.py, line 3.

The code does not comply to PEP8.

*PEP8Bear, severity NORMAL, section `pep8`.*

The issue can be fixed by applying the following patch:

```diff
--- a/modular_exponential/modular_exponential.py
+++ b/modular_exponential/modular_exponential.py
@@ -1,6 +1,7 @@
 """
 Modular Exponential
 """
+
 
 def mod_exponent(base, power, mod):
     """
```

**Comment by aviaryan** [comment]
Comment on 68e10c66a7ed217398cffbac0be92e540985c06f, file stack/stack.py, line 1.

The code does not comply to PEP8.

*PEP8Bear, severity NORMAL, section `pep8`.*

The issue can be fixed by applying the following patch:

```diff
--- a/stack/stack.py
+++ b/stack/stack.py
@@ -1,4 +1,5 @@
 class Stack(object):
+
     def __init__(self):
         self._list = []
 
```

**Comment by aashutoshrathi** [comment]
@aviaryan @singhpratyush take a look, Should I change something here ?

**Comment by Monal5031** [comment]
@aashutoshrathi just recommit and squash your commits once it will pass

**Comment by aashutoshrathi** [comment]
@Monal5031 why ?

**Pull request closed without merging**
