### PR TITLE
Removed error showed by codacy

### LINKED ISSUE #456: Remove issues pointed by Codacy
#### This issue is about [Codacy code check issues](https://www.codacy.com/app/iiitv/algos/dashboard).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by devshiva619**
Fixes #456 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [ ] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by singhpratyush** [comment]
Hi! Thanks for showing interest in contributing to this repository.

Please make sure that you have ticked the points mentioned in PR description correctly.

Thanks again!

**Comment by devshiva619** [comment]
@singhpratyush Hey I am seeing `Merging is Blocked` is that issue?

**Comment by aashutoshrathi** [comment]
Fix Travis Issues, merging is only done by Maintainers

**Comment by devshiva619** [comment]
@singhpratyush please review my PR

**Comment by devshiva619** [comment]
@aashutoshrathi can you review my PR please.

**Comment by devshiva619** [comment]
@aashutoshrathi please review my PR its been 12hrs I have submitted, and please let me know if something needs to be done.

**Pull request merged**
