### PR TITLE
Added Breadth First Traversal [JAVA]

### LINKED ISSUE #814: Breadth First Traversal [JAVA]
#### This issue is about [Breadth First Traversal] [Breadth First Traversal](https://en.wikipedia.org/wiki/Graph_traversal)

- [X] Issue Title is in form `Algo/DS Name [Language]`.
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This Algo/DS is worth adding to this repository.
- [X] Assign this issue to me (I want to work on this).
	- [X] I ensure that I am not already assigned to 2 or more issues.
- [X] I will send my PR only after I'm assigned to this issue by any maintainer.
- [X] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by satyacasm**
Fixes #814 

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [X] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [X] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [X] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [X] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [X] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [X] This pull request shall only be reviewed and merged once the Travis build passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [X] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

.
image

image

### CODE REVIEW

**Review by kalashshah — CHANGES_REQUESTED** [review]
Format code, remove blank lines, switch to camel case, and add access modifiers.

**Comment by satyacasm** [comment]
Done

**Review by kalashshah — CHANGES_REQUESTED** [review]
Filename should be derived from the folder name. (eg longest_common_subsequence becomes longestCommonSubsequence.c or LongestCommonSubsequence.java).
Change file name to Camel Casing

**Comment by satyacasm** [comment]
Changed file name to camel case.

**Review by kalashshah — APPROVED** [review]

**Pull request merged**
