### PR TITLE
Added Linear Search [C#]

### LINKED ISSUE #470: Linear Search [C#]
#### This issue is about [Linear Search](https://en.wikipedia.org/wiki/Linear_search).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by DimaMukhin**
Fixes #470

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

**Comment by singhpratyush** [comment]
Hi! Thanks for showing interest in contributing to this repository.

Please make sure that you have ticked the points mentioned in PR description correctly.

Thanks again!

**Comment by aashutoshrathi** [comment]
@singhpratyush The Travis Build is failing due to spacing in comments, can this be ignored?

**Comment by Monal5031** [comment]
@aashutoshrathi No, it will cause other PRs to fail too.

**Comment by DimaMukhin** [comment]
Is there a way to test commits with Travis without committing?

**Comment by Monal5031** [comment]
@DimaMukhin For spacing/indentation issues you can test locally using `coala`.

**Pull request merged**
